In [4]:
from StartingCandidateGenerator import StartingCandidateGenerator as SCG
from DataBaseInterface import DataBaseInterface as DBI
from CrossOperation import CrossOperation as CO
"Import necessary to fix atoms in the slab"
from ase.constraints import FixAtoms
from ase import Atoms
from ase.io import read
from generate_ceo2 import create_ceo2_111 as ceo2Slab
import numpy as np
from ase.visualize import view
import numpy as np
from ase.optimize import BFGS
from ase.calculators.emt import EMT

#--------------------------Define the fitness fucntion for your atoms-----------------------"

def fitness_function(atoms,env,reference = 0.0,au_energy = 0.0)-> float:

    at_num= atoms.get_atomic_numbers()
    pt_num = np.count_nonzero(at_num == 78)
    au_num= np.count_nonzero(at_num == 79)

    fre = atoms.get_potential_energy() - reference - au_num * (au_energy) - au_num*env
    return fre

#---------------------------Generate static part of the system------------------------------"
slab = ceo2Slab(number_of_layers=1,repetitions = (5,5,1),vacuum=12.0)
a = 12.0
slab = Atoms(cell=[a,a,a],
             pbc=True)
c = FixAtoms(indices=np.arange(len(slab)))
slab.set_constraint(c)
#If slab atoms arent fixed they will be generated  for all structures, but will be relaxed!"

#---------------------------Generate constant part of the system------------------------------"
#Part of the system that can be relaxed but that does not vary in number over the duration of the search"
constant = Atoms('Pt1')
print(constant.get_scaled_positions())

#---------Generate variable part of the system-(Single atom types only)------------------"
#Part of the system that can be relaxed and that varyies in number over the duration of the search"
#
variable_type = Atoms('Au')
#Considered number of variable type atoms n the search"
variable_range = [1,2,3,4,5,7,8,9,10]

#---------------------------Define starting population--------------------------------"

candidateGenerator = SCG(slab,constant,variable_type,variable_range)
crossing = CO(slab,constant,variable_type,variable_range,stc_change_chance = 0.5)
db = DBI('databaseGA.db')
population = 25

starting_pop = candidateGenerator.get_starting_population(population_size=population)

#-----------------------------------Define Calculator----------------------------------------"

calc = EMT()

#Get Reference energies##########
constant.cell = slab.get_cell()
variable_type.cell = slab.get_cell()

constant.calc = calc
dyn = BFGS(constant)
dyn.run(steps=100, fmax=0.05)
ref = constant.get_potential_energy()
variable_type.calc = calc
dyn = BFGS(variable_type)
dyn.run(steps=100, fmax=0.05)
au_en = variable_type.get_potential_energy()
#####################################



for i in starting_pop:
    db.add_unrelaxed_candidate(i )

#---------------------------------Relax initial structures-----------------------------------"
env = -0.5 #Environment chem pot 
while db.get_number_of_unrelaxed_candidates() > 0:

    atoms = db.get_first_unrelaxed()
    
    atoms.calc = calc
    dyn = BFGS(atoms)
    dyn.run(steps=100, fmax=0.05)
    atoms.get_potential_energy()
    
    atoms.info['key_value_pairs']['raw_score'] = -fitness_function(atoms,env,reference = ref, au_energy = au_en)
   
    db.update_to_relaxed(atoms.info['key_value_pairs']['dbid'],atoms)

#--------------------------------------Find better stoich to srtart eval----------------------------
#Overall fitness value
steps = 10
sub_steps = 20
for i in range(steps):
    for j in range(sub_steps):
        atomslist = db.get_better_candidates(n=10)
        #Choose two of the most stable structures to pair
        cand1 = np.random.randint(0,10)
        cand2 = np.random.randint(0,10)
        while cand1 == cand2:
            cand2 = np.random.randint(0,10)
            
        #Mate the particles
        res  = crossing.cross(atomslist[cand1],atomslist[cand2])
        if(res is not None):
            if(len(atomslist[cand1])!= len(res) and len(atomslist[cand2]) != len(res)):
                print("--------------STCCHANGE-----------------")
            db.add_unrelaxed_candidate(res)
            
    
    while db.get_number_of_unrelaxed_candidates() > 0:

        atoms = db.get_first_unrelaxed()

        atoms.calc = calc
        dyn = BFGS(atoms)
        dyn.run(steps=100, fmax=0.05)
        atoms.get_potential_energy()

        atoms.info['key_value_pairs']['raw_score'] = -fitness_function(atoms,env,reference = ref, au_energy = au_en)

        db.update_to_relaxed(atoms.info['key_value_pairs']['dbid'],atoms)
        
atomslist = db.get_better_candidates(n=2)
for at in atomslist:
    print(at.numbers)
view(atomslist[0])

[[0. 0. 0.]]
[78 79]
[78 79]
[78 79 79]
[78 79 79]
[78 79 79 79]
[78 79 79 79]
[78 79 79 79 79]
[78 79 79 79 79]
[78 79 79 79 79 79]
[78 79 79 79 79 79]
[78 79 79 79 79 79 79 79]
[78 79 79 79 79 79 79 79]
[78 79 79 79 79 79 79 79 79]
[78 79 79 79 79 79 79 79 79]
[78 79 79 79 79 79 79 79 79 79]
[78 79 79 79 79 79 79 79 79 79]
[78 79 79 79 79 79 79 79 79 79 79]
[78 79 79 79 79 79 79 79 79 79 79]
      Step     Time          Energy         fmax
BFGS:    0 15:19:28        5.850000        0.0000
      Step     Time          Energy         fmax
BFGS:    0 15:19:28        3.800000        0.0000
      Step     Time          Energy         fmax
BFGS:    0 15:19:29        4.149172        5.3566
BFGS:    1 15:19:29        3.413986        3.9886
BFGS:    2 15:19:29        4.433464       14.2824
BFGS:    3 15:19:29        3.132328        2.3275
BFGS:    4 15:19:29        3.055124        1.1533
BFGS:    5 15:19:29        3.035136        0.2731
BFGS:    6 15:19:29        3.034113        0.0230
      

BFGS:   31 15:19:29        5.180436        0.5003
BFGS:   32 15:19:29        5.171051        0.2768
BFGS:   33 15:19:29        5.168043        0.1251
BFGS:   34 15:19:29        5.167238        0.0582
BFGS:   35 15:19:29        5.167045        0.0526
BFGS:   36 15:19:29        5.166574        0.0747
BFGS:   37 15:19:29        5.166092        0.0908
BFGS:   38 15:19:29        5.165476        0.0823
BFGS:   39 15:19:29        5.165088        0.0655
BFGS:   40 15:19:29        5.164817        0.0737
BFGS:   41 15:19:29        5.164471        0.0823
BFGS:   42 15:19:29        5.163510        0.1166
BFGS:   43 15:19:29        5.159629        0.2579
BFGS:   44 15:19:29        5.135779        0.6464
BFGS:   45 15:19:29        5.030577        0.8422
BFGS:   46 15:19:29        4.852078        0.9570
BFGS:   47 15:19:29        5.344938        5.4276
BFGS:   48 15:19:29        4.826480        0.7725
BFGS:   49 15:19:29        4.819869        0.7431
BFGS:   50 15:19:29        4.806946        0.7724


BFGS:   69 15:19:30        8.713254        0.1938
BFGS:   70 15:19:30        8.692502        0.3955
BFGS:   71 15:19:30        8.673830        1.0590
BFGS:   72 15:19:30        8.662731        0.8545
BFGS:   73 15:19:30        8.635921        1.1372
BFGS:   74 15:19:30        8.580235        1.1975
BFGS:   75 15:19:30        8.462635        1.0633
BFGS:   76 15:19:30        8.336612        0.8690
BFGS:   77 15:19:30        8.385743        1.6219
BFGS:   78 15:19:30        8.305147        0.6921
BFGS:   79 15:19:30        8.293472        0.7717
BFGS:   80 15:19:30        8.273528        0.7183
BFGS:   81 15:19:30        8.256284        0.6120
BFGS:   82 15:19:30        8.230176        0.7019
BFGS:   83 15:19:30        8.130235        1.1678
BFGS:   84 15:19:30        8.080549        1.3139
BFGS:   85 15:19:30        8.012959        0.8238
BFGS:   86 15:19:30        7.965582        0.7058
BFGS:   87 15:19:30        7.918680        0.7011
BFGS:   88 15:19:30        7.908858        1.0638


BFGS:   29 15:19:30        9.936386        1.1190
BFGS:   30 15:19:30        9.847712        1.2384
BFGS:   31 15:19:30       10.131654        4.4641
BFGS:   32 15:19:30        9.844151        1.5057
BFGS:   33 15:19:30        9.857500        1.4494
BFGS:   34 15:19:30        9.720535        1.0650
BFGS:   35 15:19:30        9.659690        1.0272
BFGS:   36 15:19:30        9.566031        1.0643
BFGS:   37 15:19:30        9.550009        2.1542
BFGS:   38 15:19:30        9.382426        0.6689
BFGS:   39 15:19:30        9.337666        0.5824
BFGS:   40 15:19:30        9.306586        0.5104
BFGS:   41 15:19:30        9.296439        0.3969
BFGS:   42 15:19:30        9.281280        0.2553
BFGS:   43 15:19:30        9.270860        0.2290
BFGS:   44 15:19:30        9.262040        0.1789
BFGS:   45 15:19:30        9.258817        0.1233
BFGS:   46 15:19:30        9.257769        0.0718
BFGS:   47 15:19:30        9.257160        0.0718
BFGS:   48 15:19:30        9.256705        0.0825


BFGS:   91 15:19:31        6.701110        0.1903
BFGS:   92 15:19:31        6.698806        0.1883
BFGS:   93 15:19:31        6.696406        0.1880
BFGS:   94 15:19:31        6.693260        0.1754
BFGS:   95 15:19:31        6.689515        0.1839
BFGS:   96 15:19:31        6.683476        0.1784
BFGS:   97 15:19:31        6.676313        0.1451
BFGS:   98 15:19:31        6.673450        0.0815
BFGS:   99 15:19:31        6.672694        0.0344
      Step     Time          Energy         fmax
BFGS:    0 15:19:31       20.592158       20.5811
BFGS:    1 15:19:31       14.439677        2.7115
BFGS:    2 15:19:31       14.173585        1.8678
BFGS:    3 15:19:31       13.682596        2.1583
BFGS:    4 15:19:31       12.919724        2.9845
BFGS:    5 15:19:31       12.199946        5.0973
BFGS:    6 15:19:31       11.853501        7.3388
BFGS:    7 15:19:31       11.294953        3.5395
BFGS:    8 15:19:31       10.780240        2.3247
BFGS:    9 15:19:31       10.503169        2.0950
B

BFGS:   92 15:19:32        9.598626        0.3146
BFGS:   93 15:19:32        9.571291        0.3504
BFGS:   94 15:19:32        9.542672        0.3123
BFGS:   95 15:19:32        9.525538        0.2784
BFGS:   96 15:19:32        9.512971        0.2475
BFGS:   97 15:19:32        9.503417        0.1087
BFGS:   98 15:19:32        9.501939        0.1046
BFGS:   99 15:19:32        9.500225        0.0912
BFGS:  100 15:19:32        9.499125        0.0931
      Step     Time          Energy         fmax
BFGS:    0 15:19:32       16.687007       12.0021
BFGS:    1 15:19:32       14.683220        2.6553
BFGS:    2 15:19:32       14.128756        2.2519
BFGS:    3 15:19:32       13.554457        2.9994
BFGS:    4 15:19:32       13.134079        2.5696
BFGS:    5 15:19:32       12.235168        1.7164
BFGS:    6 15:19:32       12.277965        3.4976
BFGS:    7 15:19:32       12.037115        1.1695
BFGS:    8 15:19:32       11.979129        0.9858
BFGS:    9 15:19:32       11.820389        1.0213
B

BFGS:   52 15:19:33        8.732725        0.3433
BFGS:   53 15:19:33        8.703637        0.3795
BFGS:   54 15:19:33        8.693791        0.3041
BFGS:   55 15:19:33        8.687401        0.2111
BFGS:   56 15:19:33        8.680723        0.2928
BFGS:   57 15:19:33        8.674564        0.2984
BFGS:   58 15:19:33        8.666625        0.1823
BFGS:   59 15:19:33        8.660320        0.1856
BFGS:   60 15:19:33        8.656397        0.1609
BFGS:   61 15:19:33        8.652886        0.1427
BFGS:   62 15:19:33        8.649800        0.0834
BFGS:   63 15:19:33        8.647954        0.1119
BFGS:   64 15:19:33        8.646835        0.1235
BFGS:   65 15:19:33        8.645684        0.1074
BFGS:   66 15:19:33        8.644531        0.0889
BFGS:   67 15:19:33        8.642975        0.0989
BFGS:   68 15:19:33        8.641044        0.1072
BFGS:   69 15:19:33        8.638793        0.1308
BFGS:   70 15:19:33        8.636336        0.1261
BFGS:   71 15:19:33        8.633437        0.1494


BFGS:   21 15:19:34        7.143866        0.4042
BFGS:   22 15:19:34        7.131976        0.3649
BFGS:   23 15:19:34        7.119514        0.3176
BFGS:   24 15:19:34        7.101924        0.3801
BFGS:   25 15:19:34        7.074641        0.5006
BFGS:   26 15:19:34        7.044168        0.6938
BFGS:   27 15:19:34        7.010571        0.5551
BFGS:   28 15:19:34        6.975749        0.5841
BFGS:   29 15:19:34        6.939788        0.4774
BFGS:   30 15:19:34        6.927398        0.3624
BFGS:   31 15:19:34        6.919852        0.3343
BFGS:   32 15:19:34        6.905589        0.2764
BFGS:   33 15:19:34        6.886654        0.3492
BFGS:   34 15:19:34        6.872961        0.3420
BFGS:   35 15:19:34        6.861826        0.2729
BFGS:   36 15:19:34        6.848494        0.2534
BFGS:   37 15:19:34        6.840853        0.2336
BFGS:   38 15:19:34        6.832376        0.2202
BFGS:   39 15:19:34        6.822349        0.2157
BFGS:   40 15:19:35        6.813854        0.3474


BFGS:   59 15:19:35        7.474473        0.3429
BFGS:   60 15:19:35        7.457830        0.3579
BFGS:   61 15:19:35        7.443995        0.3852
BFGS:   62 15:19:35        7.428134        0.2895
BFGS:   63 15:19:35        7.411227        0.2539
BFGS:   64 15:19:35        7.400277        0.2301
BFGS:   65 15:19:35        7.388368        0.2508
BFGS:   66 15:19:35        7.373661        0.2340
BFGS:   67 15:19:35        7.357153        0.3148
BFGS:   68 15:19:35        7.333221        0.4145
BFGS:   69 15:19:35        7.311812        0.4199
BFGS:   70 15:19:35        7.285822        0.4184
BFGS:   71 15:19:35        7.268151        0.4128
BFGS:   72 15:19:35        7.252428        0.3036
BFGS:   73 15:19:35        7.238316        0.2127
BFGS:   74 15:19:35        7.229799        0.2173
BFGS:   75 15:19:35        7.224392        0.2777
BFGS:   76 15:19:35        7.217760        0.2849
BFGS:   77 15:19:35        7.204335        0.2512
BFGS:   78 15:19:35        7.184596        0.2748


BFGS:   17 15:19:36        8.147197        0.1863
BFGS:   18 15:19:36        8.142246        0.2000
BFGS:   19 15:19:36        8.136792        0.1809
BFGS:   20 15:19:36        8.131643        0.1820
BFGS:   21 15:19:36        8.127370        0.2165
BFGS:   22 15:19:36        8.123126        0.2371
BFGS:   23 15:19:36        8.117265        0.2675
BFGS:   24 15:19:36        8.107955        0.3159
BFGS:   25 15:19:36        8.096066        0.3308
BFGS:   26 15:19:36        8.084177        0.3758
BFGS:   27 15:19:36        8.069874        0.3086
BFGS:   28 15:19:36        8.061667        0.2454
BFGS:   29 15:19:36        8.053890        0.2295
BFGS:   30 15:19:36        8.048370        0.1666
BFGS:   31 15:19:36        8.045243        0.1643
BFGS:   32 15:19:36        8.042223        0.1387
BFGS:   33 15:19:36        8.038723        0.1406
BFGS:   34 15:19:36        8.036063        0.1220
BFGS:   35 15:19:36        8.034667        0.0773
BFGS:   36 15:19:36        8.033859        0.0938


BFGS:   79 15:19:37        6.558740        0.2122
BFGS:   80 15:19:37        6.554838        0.1878
BFGS:   81 15:19:37        6.551180        0.1400
BFGS:   82 15:19:37        6.546814        0.1558
BFGS:   83 15:19:37        6.542036        0.1743
BFGS:   84 15:19:37        6.538614        0.1469
BFGS:   85 15:19:37        6.536991        0.0830
BFGS:   86 15:19:37        6.536112        0.0711
BFGS:   87 15:19:37        6.535089        0.0737
BFGS:   88 15:19:37        6.533353        0.0751
BFGS:   89 15:19:37        6.531727        0.0976
BFGS:   90 15:19:37        6.530837        0.0927
BFGS:   91 15:19:37        6.530297        0.0779
BFGS:   92 15:19:37        6.529562        0.0667
BFGS:   93 15:19:37        6.528272        0.0939
BFGS:   94 15:19:37        6.526438        0.1154
BFGS:   95 15:19:37        6.524797        0.1095
BFGS:   96 15:19:37        6.523605        0.0916
BFGS:   97 15:19:37        6.522338        0.0976
BFGS:   98 15:19:37        6.520811        0.0838


BFGS:    5 15:19:38        7.289890        0.5705
BFGS:    6 15:19:38        7.235222        0.7529
BFGS:    7 15:19:38        7.174263        0.8538
BFGS:    8 15:19:38        7.113263        0.8227
BFGS:    9 15:19:38        7.076781        0.8404
BFGS:   10 15:19:38        7.036503        0.6619
BFGS:   11 15:19:38        7.014274        0.4769
BFGS:   12 15:19:38        6.988101        0.3533
BFGS:   13 15:19:38        6.968015        0.3453
BFGS:   14 15:19:38        6.958131        0.2485
BFGS:   15 15:19:38        6.954349        0.1848
BFGS:   16 15:19:38        6.949712        0.1430
BFGS:   17 15:19:38        6.944894        0.1739
BFGS:   18 15:19:38        6.940080        0.2195
BFGS:   19 15:19:38        6.935433        0.2247
BFGS:   20 15:19:38        6.931573        0.1497
BFGS:   21 15:19:38        6.929458        0.0645
BFGS:   22 15:19:38        6.928573        0.0391
      Step     Time          Energy         fmax
BFGS:    0 15:19:38       13.991772        0.0282
 

      Step     Time          Energy         fmax
BFGS:    0 15:19:40        9.499125        0.0931
BFGS:    1 15:19:40        9.498649        0.0867
BFGS:    2 15:19:40        9.494697        0.0895
BFGS:    3 15:19:40        9.494314        0.0812
BFGS:    4 15:19:40        9.492090        0.0707
BFGS:    5 15:19:40        9.491578        0.0776
BFGS:    6 15:19:40        9.490651        0.0915
BFGS:    7 15:19:40        9.489816        0.0755
BFGS:    8 15:19:40        9.489037        0.0613
BFGS:    9 15:19:40        9.488506        0.0584
BFGS:   10 15:19:40        9.488024        0.0610
BFGS:   11 15:19:40        9.487548        0.0611
BFGS:   12 15:19:40        9.487060        0.0716
BFGS:   13 15:19:40        9.486588        0.0705
BFGS:   14 15:19:40        9.486088        0.0747
BFGS:   15 15:19:40        9.485532        0.0940
BFGS:   16 15:19:40        9.484984        0.0803
BFGS:   17 15:19:40        9.484536        0.0693
BFGS:   18 15:19:40        9.484112        0.0774
B

BFGS:   60 15:19:41        9.329507        0.8016
BFGS:   61 15:19:41        9.308723        1.2184
BFGS:   62 15:19:41        9.284279        0.7654
BFGS:   63 15:19:41        9.252007        0.6775
BFGS:   64 15:19:41        9.196751        0.5929
BFGS:   65 15:19:41        9.137291        0.5672
BFGS:   66 15:19:41        9.073702        0.7564
BFGS:   67 15:19:41        9.014505        0.7728
BFGS:   68 15:19:41        8.957799        0.6244
BFGS:   69 15:19:41        8.932897        0.5022
BFGS:   70 15:19:41        8.895697        0.4089
BFGS:   71 15:19:41        8.875666        0.4491
BFGS:   72 15:19:41        8.857008        0.4105
BFGS:   73 15:19:41        8.840757        0.4287
BFGS:   74 15:19:41        8.830245        0.2730
BFGS:   75 15:19:41        8.821258        0.3124
BFGS:   76 15:19:41        8.804910        0.3901
BFGS:   77 15:19:41        8.782056        0.4430
BFGS:   78 15:19:41        8.766089        0.4337
BFGS:   79 15:19:41        8.749726        0.3032


BFGS:   15 15:19:41        9.236491        0.0515
BFGS:   16 15:19:41        9.236199        0.0577
BFGS:   17 15:19:41        9.235839        0.0617
BFGS:   18 15:19:41        9.235469        0.0704
BFGS:   19 15:19:41        9.235200        0.0485
      Step     Time          Energy         fmax
BFGS:    0 15:19:42        6.681686        0.2985
BFGS:    1 15:19:42        6.678618        0.2850
BFGS:    2 15:19:42        6.647816        0.2752
BFGS:    3 15:19:42        6.643478        0.2539
BFGS:    4 15:19:42        6.631671        0.2115
BFGS:    5 15:19:42        6.628283        0.2695
BFGS:    6 15:19:42        6.618440        0.3232
BFGS:    7 15:19:42        6.611301        0.2421
BFGS:    8 15:19:42        6.605390        0.1552
BFGS:    9 15:19:42        6.602587        0.1164
BFGS:   10 15:19:42        6.600624        0.1513
BFGS:   11 15:19:42        6.598553        0.1487
BFGS:   12 15:19:42        6.596576        0.0914
BFGS:   13 15:19:42        6.595227        0.1059
B

BFGS:   12 15:19:45        6.587007        0.0774
BFGS:   13 15:19:45        6.586330        0.0663
BFGS:   14 15:19:45        6.585825        0.0529
BFGS:   15 15:19:45        6.585284        0.0626
BFGS:   16 15:19:45        6.584744        0.0620
BFGS:   17 15:19:45        6.584337        0.0466
      Step     Time          Energy         fmax
BFGS:    0 15:19:45        6.672152        0.3006
BFGS:    1 15:19:45        6.665707        0.2805
BFGS:    2 15:19:45        6.637150        0.2507
BFGS:    3 15:19:45        6.632711        0.2027
BFGS:    4 15:19:45        6.614973        0.1414
BFGS:    5 15:19:45        6.612458        0.1527
BFGS:    6 15:19:45        6.606395        0.1562
BFGS:    7 15:19:45        6.600564        0.1542
BFGS:    8 15:19:45        6.595317        0.1637
BFGS:    9 15:19:45        6.592884        0.1688
BFGS:   10 15:19:45        6.590548        0.1378
BFGS:   11 15:19:45        6.588274        0.0965
BFGS:   12 15:19:45        6.587007        0.0774
B

BFGS:   78 15:19:45        7.162622        0.2940
BFGS:   79 15:19:45        7.146201        0.3295
BFGS:   80 15:19:45        7.134192        0.2716
BFGS:   81 15:19:45        7.116216        0.2226
BFGS:   82 15:19:45        7.096130        0.2081
BFGS:   83 15:19:45        7.078002        0.1996
BFGS:   84 15:19:45        7.067799        0.1920
BFGS:   85 15:19:45        7.060937        0.1610
BFGS:   86 15:19:45        7.056738        0.1471
BFGS:   87 15:19:45        7.050153        0.1366
BFGS:   88 15:19:45        7.040482        0.1567
BFGS:   89 15:19:45        7.030740        0.1655
BFGS:   90 15:19:45        7.023859        0.1672
BFGS:   91 15:19:45        7.018759        0.1704
BFGS:   92 15:19:45        7.014763        0.1672
BFGS:   93 15:19:45        7.009693        0.1565
BFGS:   94 15:19:45        7.002914        0.1867
BFGS:   95 15:19:45        6.996253        0.1966
BFGS:   96 15:19:45        6.990500        0.1616
BFGS:   97 15:19:45        6.986969        0.1234


BFGS:   44 15:19:46        7.431560        0.1610
BFGS:   45 15:19:46        7.427552        0.1876
BFGS:   46 15:19:46        7.421062        0.2714
BFGS:   47 15:19:46        7.411919        0.3201
BFGS:   48 15:19:46        7.400797        0.2877
BFGS:   49 15:19:46        7.390870        0.2546
BFGS:   50 15:19:46        7.385165        0.1947
BFGS:   51 15:19:46        7.381751        0.2349
BFGS:   52 15:19:46        7.377334        0.1548
BFGS:   53 15:19:46        7.372325        0.1267
BFGS:   54 15:19:46        7.365035        0.1470
BFGS:   55 15:19:46        7.362248        0.1668
BFGS:   56 15:19:46        7.357597        0.1685
BFGS:   57 15:19:46        7.354148        0.1860
BFGS:   58 15:19:46        7.349963        0.1783
BFGS:   59 15:19:46        7.346779        0.1258
BFGS:   60 15:19:46        7.344780        0.1323
BFGS:   61 15:19:46        7.343505        0.1226
BFGS:   62 15:19:46        7.341736        0.1126
BFGS:   63 15:19:46        7.339278        0.1239


BFGS:    1 15:19:49        7.184413        0.7511
BFGS:    2 15:19:49        7.115344        0.4237
BFGS:    3 15:19:49        7.109364        0.3089
BFGS:    4 15:19:49        7.095504        0.1924
BFGS:    5 15:19:49        7.082367        0.2910
BFGS:    6 15:19:49        7.073605        0.3090
BFGS:    7 15:19:49        7.067853        0.1994
BFGS:    8 15:19:49        7.064855        0.0802
BFGS:    9 15:19:49        7.064226        0.0523
BFGS:   10 15:19:49        7.063942        0.0470
      Step     Time          Energy         fmax
BFGS:    0 15:19:49        6.584337        0.0466
      Step     Time          Energy         fmax
BFGS:    0 15:19:49        6.584337        0.0466
      Step     Time          Energy         fmax
BFGS:    0 15:19:49        6.584337        0.0466
      Step     Time          Energy         fmax
BFGS:    0 15:19:49        6.584337        0.0466
      Step     Time          Energy         fmax
BFGS:    0 15:19:50        6.584337        0.0466
     

      Step     Time          Energy         fmax
BFGS:    0 15:19:51        6.584337        0.0466
--------------STCCHANGE-----------------
--------------STCCHANGE-----------------
--------------STCCHANGE-----------------
      Step     Time          Energy         fmax
BFGS:    0 15:19:54        6.196214        3.0739
BFGS:    1 15:19:54        5.746230        2.6282
BFGS:    2 15:19:54        5.623924        3.7489
BFGS:    3 15:19:54        5.227362        1.0251
BFGS:    4 15:19:54        5.180636        0.3519
BFGS:    5 15:19:54        5.173294        0.2807
BFGS:    6 15:19:54        5.171463        0.1956
BFGS:    7 15:19:54        5.168745        0.1025
BFGS:    8 15:19:54        5.168373        0.0756
BFGS:    9 15:19:54        5.168070        0.0420
      Step     Time          Energy         fmax
BFGS:    0 15:19:54        6.584337        0.0466
      Step     Time          Energy         fmax
BFGS:    0 15:19:54        6.584337        0.0466
      Step     Time          En

BFGS:    3 15:19:55        6.270362        0.2263
BFGS:    4 15:19:55        6.264623        0.0804
BFGS:    5 15:19:55        6.264030        0.0875
BFGS:    6 15:19:55        6.262059        0.0900
BFGS:    7 15:19:55        6.261198        0.0965
BFGS:    8 15:19:55        6.260159        0.1084
BFGS:    9 15:19:55        6.259054        0.1085
BFGS:   10 15:19:55        6.257502        0.0922
BFGS:   11 15:19:55        6.255918        0.1200
BFGS:   12 15:19:55        6.254419        0.1311
BFGS:   13 15:19:55        6.253204        0.0962
BFGS:   14 15:19:55        6.252254        0.0928
BFGS:   15 15:19:55        6.251464        0.0837
BFGS:   16 15:19:55        6.250711        0.0663
BFGS:   17 15:19:55        6.249959        0.0797
BFGS:   18 15:19:55        6.249348        0.0632
BFGS:   19 15:19:55        6.249003        0.0429
      Step     Time          Energy         fmax
BFGS:    0 15:19:55        6.584337        0.0466
--------------STCCHANGE-----------------
----------

BFGS:    9 15:19:58        6.493103        0.0549
BFGS:   10 15:19:58        6.492578        0.0529
BFGS:   11 15:19:58        6.492228        0.0463
      Step     Time          Energy         fmax
BFGS:    0 15:19:58        6.584337        0.0466
      Step     Time          Energy         fmax
BFGS:    0 15:19:59        6.584337        0.0466
      Step     Time          Energy         fmax
BFGS:    0 15:19:59        6.492228        0.0463
      Step     Time          Energy         fmax
BFGS:    0 15:19:59        6.130141        0.9845
BFGS:    1 15:19:59        6.096664        0.7514
BFGS:    2 15:19:59        6.058452        0.2870
BFGS:    3 15:19:59        6.055894        0.1848
BFGS:    4 15:19:59        6.052694        0.1291
BFGS:    5 15:19:59        6.050411        0.0906
BFGS:    6 15:19:59        6.049526        0.0937
BFGS:    7 15:19:59        6.048628        0.0848
BFGS:    8 15:19:59        6.047612        0.0936
BFGS:    9 15:19:59        6.046908        0.0792
BFGS

      Step     Time          Energy         fmax
BFGS:    0 15:20:02        5.996290        1.0223
BFGS:    1 15:20:02        5.939821        0.8146
BFGS:    2 15:20:02        5.876002        0.3879
BFGS:    3 15:20:02        5.867867        0.3572
BFGS:    4 15:20:02        5.839436        0.2363
BFGS:    5 15:20:02        5.834007        0.2191
BFGS:    6 15:20:02        5.827745        0.2596
BFGS:    7 15:20:02        5.819231        0.2529
BFGS:    8 15:20:02        5.812009        0.2018
BFGS:    9 15:20:02        5.807270        0.1640
BFGS:   10 15:20:02        5.804591        0.1623
BFGS:   11 15:20:02        5.802260        0.1299
BFGS:   12 15:20:02        5.800534        0.1200
BFGS:   13 15:20:02        5.799388        0.1108
BFGS:   14 15:20:02        5.798605        0.0785
BFGS:   15 15:20:02        5.797943        0.0776
BFGS:   16 15:20:02        5.797372        0.0777
BFGS:   17 15:20:02        5.796816        0.0682
BFGS:   18 15:20:02        5.796260        0.0635
B

BFGS:    4 15:20:07        8.325060        0.7667
BFGS:    5 15:20:07        8.314137        0.2069
BFGS:    6 15:20:07        8.313383        0.0145
      Step     Time          Energy         fmax
BFGS:    0 15:20:07        6.492228        0.0463
      Step     Time          Energy         fmax
BFGS:    0 15:20:07        6.492228        0.0463
      Step     Time          Energy         fmax
BFGS:    0 15:20:07        6.492228        0.0463
      Step     Time          Energy         fmax
BFGS:    0 15:20:07        6.817410        1.1663
BFGS:    1 15:20:07        6.773965        0.9259
BFGS:    2 15:20:07        6.714483        0.2315
BFGS:    3 15:20:07        6.710652        0.1903
BFGS:    4 15:20:07        6.708799        0.1870
BFGS:    5 15:20:07        6.683923        0.3440
BFGS:    6 15:20:07        6.671307        0.3553
BFGS:    7 15:20:07        6.659678        0.2348
BFGS:    8 15:20:07        6.653118        0.2123
BFGS:    9 15:20:07        6.647775        0.1800
BFGS

BFGS:   57 15:20:11        6.892858        0.1161
BFGS:   58 15:20:11        6.890763        0.1027
BFGS:   59 15:20:11        6.888307        0.1297
BFGS:   60 15:20:11        6.885253        0.1560
BFGS:   61 15:20:11        6.881709        0.1669
BFGS:   62 15:20:11        6.877952        0.2029
BFGS:   63 15:20:11        6.874182        0.1902
BFGS:   64 15:20:11        6.869618        0.1970
BFGS:   65 15:20:11        6.863056        0.2757
BFGS:   66 15:20:11        6.852490        0.3506
BFGS:   67 15:20:11        6.836589        0.4518
BFGS:   68 15:20:11        6.817969        0.3663
BFGS:   69 15:20:11        6.799945        0.3609
BFGS:   70 15:20:11        6.784462        0.3659
BFGS:   71 15:20:11        6.769916        0.4256
BFGS:   72 15:20:11        6.755597        0.3927
BFGS:   73 15:20:11        6.761465        0.4202
BFGS:   74 15:20:11        6.740594        0.2133
BFGS:   75 15:20:11        6.734344        0.1849
BFGS:   76 15:20:11        6.729224        0.1651


BFGS:   28 15:20:12        9.820202        0.4644
BFGS:   29 15:20:12        9.789485        0.5701
BFGS:   30 15:20:12        9.756010        0.5732
BFGS:   31 15:20:12        9.705153        0.6013
BFGS:   32 15:20:12        9.622667        1.1320
BFGS:   33 15:20:12        9.497766        1.4681
BFGS:   34 15:20:12        9.364470        1.9615
BFGS:   35 15:20:12        9.006508        2.0034
BFGS:   36 15:20:12        8.646244        2.4322
BFGS:   37 15:20:12        8.118694        2.1067
BFGS:   38 15:20:12        7.916729        1.3520
BFGS:   39 15:20:12        7.762585        1.0714
BFGS:   40 15:20:12        7.584071        0.9387
BFGS:   41 15:20:12        7.440061        1.1794
BFGS:   42 15:20:12        7.265172        1.1263
BFGS:   43 15:20:12        7.134868        0.7737
BFGS:   44 15:20:12        7.074871        0.6778
BFGS:   45 15:20:12        7.019805        0.6008
BFGS:   46 15:20:12        6.969280        0.4520
BFGS:   47 15:20:12        6.927410        0.3976


BFGS:   18 15:20:17        7.631814        1.0623
BFGS:   19 15:20:17        7.605336        0.7783
BFGS:   20 15:20:17        7.553531        0.4862
BFGS:   21 15:20:17        7.537452        0.3238
BFGS:   22 15:20:17        7.529164        0.2993
BFGS:   23 15:20:17        7.509367        0.3034
BFGS:   24 15:20:17        7.505217        0.2432
BFGS:   25 15:20:17        7.499790        0.1416
BFGS:   26 15:20:17        7.497953        0.1651
BFGS:   27 15:20:17        7.493016        0.2017
BFGS:   28 15:20:17        7.488417        0.1938
BFGS:   29 15:20:17        7.482604        0.2202
BFGS:   30 15:20:17        7.478224        0.1900
BFGS:   31 15:20:17        7.475585        0.1497
BFGS:   32 15:20:17        7.473486        0.1773
BFGS:   33 15:20:17        7.468298        0.2764
BFGS:   34 15:20:17        7.433931        0.6781
BFGS:   35 15:20:17        7.391571        1.0088
BFGS:   36 15:20:17        7.368444        0.5356
BFGS:   37 15:20:17        7.339589        0.3431


BFGS:   80 15:20:18        5.404387        0.3761
BFGS:   81 15:20:18        5.403463        0.3731
BFGS:   82 15:20:18        5.402177        0.3754
BFGS:   83 15:20:18        5.399766        0.3789
BFGS:   84 15:20:18        5.395996        0.3912
BFGS:   85 15:20:18        5.391129        0.4113
BFGS:   86 15:20:18        5.385920        0.4346
BFGS:   87 15:20:18        5.381765        0.4548
BFGS:   88 15:20:18        5.378420        0.4816
BFGS:   89 15:20:18        5.373244        0.5190
BFGS:   90 15:20:18        5.364873        0.5650
BFGS:   91 15:20:18        5.349683        0.6223
BFGS:   92 15:20:18        5.330626        0.6490
BFGS:   93 15:20:18        5.310458        0.5056
BFGS:   94 15:20:18        5.305178        0.4296
BFGS:   95 15:20:18        5.296063        0.4284
BFGS:   96 15:20:18        5.293808        0.4384
BFGS:   97 15:20:18        5.293171        0.4511
BFGS:   98 15:20:18        5.292743        0.4494
BFGS:   99 15:20:18        5.291818        0.4508


<Popen: returncode: None args: ['/home/jon/Documents/GrandCanonicalGA/ase_en...>